config/routes.rb
Rails.application.routes.draw do
  root 'blog#index'
get '/blogs' => 'blog#index', as: 'blogs'
get 'blogs/new' => 'blog#new', as: 'new'
get '/blogs/:id' => 'blog#show', as: 'blog'
get 'blogs/:id/edit'=> 'blog#edit', as: 'edit'
post 'blogs' => 'blog#create'
patch 'blogs/:id' => 'blog#update'
delete 'blogs/:id' => 'blog#destroy', as: 'delete'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
    def index
        @blogs = Blog.all
    end
    def show
        @blog = Blog.find(params[:id])
    end
    def new
        @blog = Blog.new

    end
    def create
        @blog = Blog.create(blog_params)
        if @blog.valid?
            redirect_to blogs_path
        end
    end
    def destroy
        @blog = Blog.find(params[:id])
        if @blog.destroy 
            redirect_to blogs_path
        end
    end
    def edit
        @blog = Blog.find(params[:id])
            
    end
    def update
        @blog = Blog.find(params[:id])
        @blog.update(blog_params)
            redirect_to blogs_path
        
    end
    private
    def blog_params
        params.require(:blog).permit(:title,:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/edit.html.erb
<h2>Edit this Blog</h2>

<%= form_with model: @blog, method: :patch do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.label :content %>
    <%= form.text_field :content %>
    <%= form.submit 'Edit Blog' %>
<% end %>

app/views/blog/index.html.erb
<h1> Our blogs</h1>
<% @blogs.each do |b| %>
    <ul>
      <li>
    <%= link_to b.title, blog_path(b)%>
      </li>
    </ul>
<% end %>
<%= link_to 'Add new blog', new_path%>

app/views/blog/new.html.erb
<h2>Add a new Blog</h2>

<%= form_with model: @blog do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.label :content %>
    <%= form.text_field :content %>
    <%= form.submit 'Add Blog' %>
<% end %>
<%= link_to 'back to blog list', blogs_path%>

app/views/blog/show.html.erb
<h2> <%= @blog.title%> </h2>
<p> this is a blog about: <%= @blog.content%></p> 

      <%= link_to 'back to blog list', blogs_path%>
      <%= button_to 'delete this blog', delete_path,method: :delete%>
      <%= link_to 'Edit this blog', edit_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FourStar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>